services:
  element-web:
    image: kalaksi/element-web
    # You can also use GitLab as an alternative to Docker Hub:
    # image: registry.gitlab.com/kalaksi-containers/element-web
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID
    volumes:
      - elementweb_config:/opt/element-web/config.json:ro
    ports:
      - 80:8080/tcp

volumes:
  elementweb_config: {}
